version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"

  tomcat:
    container_name: tomcat
    image: tomcat-lpsolve:v1
    restart: on-failure
    volumes:
      - ./war/app-version-1.2.war:/usr/local/tomcat/webapps/app.war
    links:
      - modelStorage
      - metaInfo
    depends_on:
      - nginx

  modelStorage:
    container_name: modelStorage
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_DB: modelStorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
    volumes:
      - ./backup/modelStorage.sql:/docker-entrypoint-initdb.d/modelStorage.sql

  metaInfo:
    container_name: metaInfo
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_DB: metaInfo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
    volumes:
      - ./backup/metaInfo.sql:/docker-entrypoint-initdb.d/metaInfo.sql
